image: jethubjhaos/{arch}-base-debian
shadow_repository: ghcr.io/jethubjhaos
build_from:
  aarch64: "arm64v8/debian:"
  armv7: "arm32v7/debian:"
  armhf: "arm32v5/debian:"
  amd64: "debian:"
  i386: "i386/debian:"
codenotary:
  signer: vb@jethome.ru
args:
  BASHIO_VERSION: 0.14.3
  TEMPIO_VERSION: 2021.09.0
  S6_OVERLAY_VERSION: 3.1.2.1
labels:
  io.hass.base.name: debian
  org.opencontainers.image.source: https://github.com/jethubjhaos/docker-base
