image: jethubjhaos/{arch}-base-python
shadow_repository: ghcr.io/jethubjhaos
build_from:
  aarch64: "jethubjhaos/aarch64-base:"
  armv7: "jethubjhaos/armv7-base:"
  armhf: "jethubjhaos/armhf-base:"
  amd64: "jethubjhaos/amd64-base:"
  i386: "jethubjhaos/i386-base:"
codenotary:
  signer: vb@jethome.ru
  base_image: vb@jethome.ru
args:
  PYTHON_VERSION: 3.9.14
  PIP_VERSION: 22.3.0
  GPG_KEY: E3FF2839C048B25C084DEBE9B26995E310250568
labels:
  io.hass.base.name: python
  org.opencontainers.image.source: https://github.com/jethubjhaos/docker-base
