image: jethubjhaos/{arch}-base-python
shadow_repository: ghcr.io/jethubjhaos
build_from:
  aarch64: "jethubjhaos/aarch64-base:"
  armv7: "jethubjhaos/armv7-base:"
  armhf: "jethubjhaos/armhf-base:"
  amd64: "jethubjhaos/amd64-base:"
  i386: "jethubjhaos/i386-base:"
codenotary:
  signer: vb@jethome.ru
  base_image: vb@jethome.ru
args:
  PYTHON_VERSION: 3.10.11
  PIP_VERSION: 23.1.1
  GPG_KEY: A035C8C19219BA821ECEA86B64E628F8D684696D
labels:
  io.hass.base.name: python
  org.opencontainers.image.source: https://github.com/jethubjhaos/docker-base
